# Generated by Django 3.2 on 2023-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230926_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=256, verbose_name='Код подтверждения'),
        ),
    ]
