# Generated by Django 3.2 on 2023-10-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231010_1710'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myuser',
            name='unique_username_email',
        ),
    ]
